apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps-n-magic2
spec:
  selector:
    matchLabels:
      run: maps-n-magic2
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        run: maps-n-magic2
    spec:
      containers:
        - name: maps-n-magic2
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3001
          env:
            - name: SKIP_PREFLIGHT_CHECK
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: SKIP_PREFLIGHT_CHECK
            - name: DROPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: admin-client
                  key: dropboxToken
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: PGPORT
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: PGDATABASE
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
