# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  env: developer
  skipPreflightCheck: true
  dbHost: postgres13
  dbPort: 5432
  dbName: mm
  services:
    gateway: https://gateway.evarun.ru
    position: http://position
    billing: http://billing
    push: http://push
    modelEngine: http://model-engine
    modelsManager: http://models-manager

image:
  repository: sr2020/maps-n-magic2
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80

# resources
resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
